version: '3.9'
services:
  bird:
    container_name: bird
    build:
      context: ./bird/
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    network_mode: host
    volumes:
      - ./bird/run:/var/run/bird
      - ./bird/config:/etc/bird:rw
      - ./update-routes/lists:/opt/

  coredns:
    build:
      context: ./coredns/
      dockerfile: Dockerfile
    container_name: coredns
    restart: always
    ports:
      - "${VPN_INTERNAL_IP}:53:53/tcp"
      - "${VPN_INTERNAL_IP}:53:53/udp"
    volumes:
      - './coredns/config:/etc/coredns'

  update-routes:
    build:
      context: ./update-routes/
      dockerfile: Dockerfile
    container_name: update-routes
    restart: always
    command: bash -c 'while true; do ./chklist.sh; sleep 3600; done;'
    volumes:
      - ./bird/run:/var/run/bird
      - ./update-routes/lists:/opt/lists
    depends_on:
      - bird
